language: scala
dist: trusty
sudo: false

scala:
  - 2.11.11
  - 2.12.2

jdk:
  - oraclejdk8
  - openjdk8

script: sbt ++$TRAVIS_SCALA_VERSION coverage test it:test
after_success: sbt ++$TRAVIS_SCALA_VERSION coveralls
